In [1]:
from bs4 import BeautifulSoup
from fuzzywuzzy import fuzz
import pandas as pd
import requests
from us import states

from team import dataframe
from data.soup_helpers import get_table

In [2]:
df = dataframe.get_all_d1_schools()
dataframe.add_tournament_rankings_to_dataframe_from_csv(df, "test/data/elite8.csv")
df = dataframe.filter_none_values(df, "Tournament Ranking")
dataframe.add_ap_rankings_to_dataframe(df)
display(df)

,School,Nickname,Home arena,Conference,Tournament appearances,Final Four appearances,Championship wins,AP Ranking,Tournament Ranking
22,Duke University,Blue Devils,Cameron Indoor Stadium,ACC,"(44) 1955, 1960, 1963, 1964, 1966, 1978, 1979,...","(17) 1963, 1964, 1966, 1978, 1986, 1988, 1989,...","(5) 1991, 1992, 2001, 2010, 2015",13,1
31,Syracuse University,Orange,Carrier Dome,ACC,"(41) 1957, 1966, 1973, 1974, 1975, 1976, 1977,...","(6) 1975, 1987, 1996, 2003, 2013, 2016",(1) 2003,24,8
73,Villanova University,Wildcats,Finneran Pavilion,Big East,"(43) 1939, 1949, 1951, 1955, 1962, 1964, 1969,...","(7) 1939, 1971*, 1985, 2009, 2016, 2018, 2022","(3) 1985, 2016, 2018",12,2
81,University of Northern Colorado,Bears,Butler–Hancock Sports Pavilion,Big Sky,(1) 2011,(0),(0),25,2
115,University of Texas at Austin,Longhorns,Moody Center,Big 12,"(36) 1939, 1943, 1947, 1960, 1963, 1972, 1974,...","(3) 1943, 1947, 2003",(0),23,3
180,Mount St. Mary's University,Mountaineers,Knott Arena,MAAC,"(6) 1995, 1999, 2008, 2014, 2017, 2021",(0),(0),None,4
285,The Citadel,Bulldogs,McAlister Field House,Southern,(0),(0),(0),19,5
341,Gonzaga University,Bulldogs,McCarthey Athletic Center,West Coast,"(24) 1995, 1999, 2000, 2001, 2002, 2003, 2004,...","(2) 2017, 2021",(0),6,1

In [3]:
display(df.loc[df["School"] == "Gonzaga University"])
display(df.loc[df["School"] == "Syracuse University"])
display(df.loc[df["School"] == "University of Texas at Austin"])

,School,Nickname,Home arena,Conference,Tournament appearances,Final Four appearances,Championship wins,AP Ranking,Tournament Ranking
341,Gonzaga University,Bulldogs,McCarthey Athletic Center,West Coast,"(24) 1995, 1999, 2000, 2001, 2002, 2003, 2004,...","(2) 2017, 2021",(0),6,1

,School,Nickname,Home arena,Conference,Tournament appearances,Final Four appearances,Championship wins,AP Ranking,Tournament Ranking
31,Syracuse University,Orange,Carrier Dome,ACC,"(41) 1957, 1966, 1973, 1974, 1975, 1976, 1977,...","(6) 1975, 1987, 1996, 2003, 2013, 2016",(1) 2003,24,8

,School,Nickname,Home arena,Conference,Tournament appearances,Final Four appearances,Championship wins,AP Ranking,Tournament Ranking
115,University of Texas at Austin,Longhorns,Moody Center,Big 12,"(36) 1939, 1943, 1947, 1960, 1963, 1972, 1974,...","(3) 1943, 1947, 2003",(0),23,3

## Get Colors

In [4]:
color_table = get_table("https://en.wikipedia.org/wiki/Module:College_color", 3)
colors = list()
for i, row in enumerate(color_table.find_all("tr")[2:]):
    cdata = row.find_all("td")
    name = cdata[0].string
    color1 = cdata[1].get("style").split(":")[1]
    color2 = cdata[3].get("style").split(":")[1]
    if "transparent" in color2:
        color2 = cdata[2].get("style").split(":")[1]
    colors.append((name, color1, color2))
colors[0]

('Abilene Christian Wildcats', '#4E2683', '#C5C6C8')

## All D1 Schools Table

In [26]:
URL = "https://en.wikipedia.org/wiki/List_of_NCAA_Division_I_institutions"
schools_table = get_table(URL, 1)
header = schools_table.find_all("tr")[1]
for i, row in enumerate(schools_table.find_all("tr")[2:]):
    data = row.find_all("td")
    school = data[0].find("a").string
    location = f"{data[3].find('a').string}, {data[4].find('a').string}"
    is_private = data[5].find("a").string.casefold() == "private".casefold()
    print(school, location, is_private)
    break

Abilene Christian University Abilene, TX True

In [35]:
df = pd.read_pickle("saved_static_data/school_data_dataframe.pkl")
df["primary_color"].isna().sum()
df

,School,Nickname,Home arena,Conference,Tournament appearances,Final Four appearances,Championship wins,AP Ranking,Tournament Ranking,primary_color,secondary_color,location,is_private
0,"University at Albany, SUNY",Great Danes,SEFCU Arena,America East,"(5) 2006, 2007, 2013, 2014, 2015",(0),(0),None,None,NaN,NaN,NaN,NaN
1,Binghamton University,Bearcats,Binghamton University Events Center,America East,(1) 2009,(0),(0),None,None,NaN,NaN,NaN,NaN
2,Bryant University,Bulldogs,Chace Athletic Center,America East,(1) 2022,(0),(0),None,None,black,gold,"Smithfield, RI",True
3,University of Maine,Black Bears,Alfond Arena,America East,(0),(0),(0),None,None,blue,sky blue,"Orono, ME",False
4,"University of Maryland, Baltimore County",Retrievers,Retriever Activities Center,America East,"(2) 2008, 2018",(0),(0),None,None,NaN,NaN,"Catonsville, MD",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,Stephen F. Austin State University,Lumberjacks,William R. Johnson Coliseum,WAC,"(5) 2009, 2014, 2015, 2016, 2018",(0),(0),None,None,NaN,NaN,"Nacogdoches, TX",False
359,Tarleton State University,Texans,Wisdom Gymnasium,WAC,(0),(0),(0),None,None,NaN,NaN,NaN,NaN
360,Utah Valley University,Wolverines,UCCU Center,WAC,(0),(0),(0),None,None,NaN,NaN,"Orem, UT",False
361,University of Texas at Arlington,Mavericks,College Park Center,WAC,(1) 2008,(0),(0),None,None,NaN,NaN,NaN,NaN
362,University of Texas Rio Grande Valley,Vaqueros,UTRGV Fieldhouse,WAC,(0),(0),(0),None,None,NaN,NaN,NaN,NaN

In [30]:
data = requests.get("https://www.caninejournal.com/college-colors/")
b = BeautifulSoup(data.text)
line_break_set = {"Name", "City", "Mascot", "Nickname", "Location", "Team Name", "Home of the Catamounts", "The Island University", "Marching Highland Cavaliers", "Senators"}
for line in b.find_all('li')[46:]:
    if line and ":" in line.text:
        sp = line.text.split(":")
        school = sp[0].strip()
        colors = sp[1]
        for t in line_break_set:
            colors = colors.split(t)[0].strip()
        if "&" in colors:
            color_split = colors.split("&")
            primary_color = color_split[0].strip()
            secondary_color = color_split[1].strip()
        if "," in colors:
            color_split = colors.split(",")
            primary_color = color_split[0].strip()
            secondary_color = color_split[1].split("&")[0].strip()
        if school and school not in line_break_set:
            print(f"{school}, {primary_color}, {secondary_color}")

Alabama A&M University, maroon, white
Alabama State University, black, gold
Auburn University, orange, blue
Samford University, red, blue
Troy University, cardinal, black and sliver
University of Alabama, crimson red, white
University of Alabama at Birmingham, white, gold
University of South Alabama, red, white
University of Alaska, green, yellow (gold)
University of Alaska Fairbanks, blue, gold
Arizona State University, maroon, gold
Northern Arizona University, navy, gold
University of Arizona, cardinal red, navy blue
Arkansas State University, scarlet red, black
Arkansas Tech University (ATU), green, gold
Mascot (men), green, gold
Mascot (women), green, gold
University of Arkansas, red, white
University of Arkansas at Fort Smith, blue, white
University of Arkansas at Monticello, green, white
University of Arkansas at Pine Bluff, black, gold
University of Central Arkansas, purple, white
California State University, Chico, red, white
California State University at Fullerton, white, orange
California State University at Irvine, blue, gold
California State University Long Beach, black, gold
Chapman University, cardinal, grey
Fresno State University, cardinal red, blue
Humboldt State University, green, gold.
San Diego State University, scarlet, black
San Francisco State University, purple, gold
San Jose State University, blue, gold
Santa Clara University, red, white
Stanford University, cardinal red, white
University of California, blue, gold
University of California at Los Angeles (UCLA), True blue, gold
University of Southern California, cardinal, gold
Air Force Academy (Air Force), royal blue, silver
Colorado College, gold, black
Colorado School of Mines, blue, silver
Colorado State University (Fort Collins), green, gold
Colorado State University (Pueblo), red, blue
Colorado Technical University, red, blue
Denver University, crimson, gold
Regis University, blue, gold
University of Colorado, silver, gold
University of Northern Colorado, navy blue, gold
Western State Colorado University (Gunnison), crimson, slate
University of Bridgeport, purple, white
University of Connecticut, navy blue, white
University of Hartford, scarlet red, white
Yale University, blue, white
Delaware State University, Columbia blue, cherry red
University of Delaware, blue, yellow
Howard University, blue, red
Florida Atlantic University, blue, red
Florida International University, blue, gold
Florida State University, garnet, gold
Florida Agriculture & Mechanical University, orange, green
University of North Florida, blue, gray
University of Tampa, red, gold
University of Miami, orange, green
University of Florida, orange, blue
University of South Florida, green, gold
University of Central Florida, black, gold
Armstrong Atlantic State University, maroon, gold.
Fort Valley State University, old gold, royal blue
Georgia Institute of Technology (Georgia Tech), old gold, white (navy accent)
Georgia Southern University, blue, white with gold trim
Georgia State University, blue, white
Kennesaw State University, black, gold
Mercer University, black, orange
North Georgia Tech, blue, green
University of Georgia, red, black
University of West Georgia, blue, red
Valdosta State University, red, black
University of Hawaii, green, white
Boise State University, blue, orange
Brigham Young University (Idaho), blue, gray
College of Idaho, purple, gold
Idaho State University, black, orange
Lewis-Clark State College, Columbia blue, white
Northwest Nazarene University, red, black
University of Idaho, silver, gold
Eastern Illinois University, grey, blue
Illinois State University, red, white
Knox College, purple, gold
Loyola University Chicago, maroon, gold
Northern Illinois University, red, black
Northwestern University, purple, white
Southern Illinois University, maroon, white
University of Chicago in Chicago (Hyde Park), maroon, white
University of Illinois, orange, blue
Western Illinois University, purple, gold
Ball State University, cardinal red, white
Butler University, navy blue, white
Indiana State University, royal blue, white
Indiana University, crimson, cream
Purdue University, old gold, black
University of Evansville, purple, white
University of Notre Dame, gold, navy blue
University of Indianapolis, crimson, grey
Valparaiso University, brown, gold
Drake University, blue, white
Iowa State University, cardinal, gold
University of Iowa, black, gold
University of Northern Iowa, purple, gold
Kansas State University, royal purple, white accent
University of Kansas, blue, crimson
Wichita State University, black, gold
University of Kentucky, blue, white
University of Louisville, red, black
Western Kentucky University, red, white
Grambling State University, black, gold
Louisiana College, orange, navy blue (Go Wildcats!)
Louisiana-Grambling State University, black, gold
Louisiana State University, purple, gold
Louisiana Tech University, blue, red
Southeastern Louisiana University, green, gold
Southern University, blue, gold
Tulane University, olive, blue
University of Louisiana at Lafayette, vermilion (red), white
University of Louisiana at Monroe, maroon, gold
University of New Orleans, blue, silver
Xavier University of New Orleans, white, gold
Bates, Maroon, gold
Bowdoin, black, white
Colby, blue, white
University of Maine, blue, sky blue
University of Southern Maine, blue, yellow
Goucher College, blue, gold
Loyola University (Baltimore), green, grey
McDaniel College, green, gold
Morgan State University, blue, orange
Naval Academy (Navy), navy blue, gold
University of Baltimore, blue, green
University of Maryland, black, gold
Washington College, maroon, black
Amherst College, purple, white
Boston College, maroon, gold
Boston University, scarlet red, white
College of the Holy Cross, purple, white
Curry College, purple, white
Harvard University, crimson, black
Massachusetts Institute of Technology (MIT), black, cardinal
Northeastern University (Boston), red, black
University of Massachusetts at Amherst, maroon, white
University of Massachusetts at Lowell, black, blue
Wentworth Institute of Technology, black, cardinal
Worcester Polytechnic Institute, crimson, grey
Central Michigan University, maroon, gold
Eastern Michigan University, green, white
Ferris State University, crimson, gold
Grand Valley State University, light blue, white
Kalamazoo College, orange, black
Michigan State University, green, white
Michigan Technological University, black, gold
University of Michigan, azure blue, maize
Western Michigan University, brown, gold
Bemidji State University, green, white
Minnesota State University (Mankato), purple, gold
Minnesota State University (Moorhead), red, white
Saint Cloud State University, cardinal, black
University of Minnesota, maroon, gold
University of Minnesota (Duluth), maroon, gold
University of Mississippi, navy blue, cardinal red
Mississippi State University, maroon, white
Southern Mississippi, black, gold
Lindenwood University, black, gold
Stephens College, burgundy, gold
University of Missouri, black, gold
Washington University, green, red
Montana State University, blue, gold
University of Great Falls, sky blue, harvest gold
University of Montana, maroon, silver
Creighton University, “Blue Jay” blue, white
University of Nebraska, scarlet, cream
University of Nebraska (Kearney), blue, gold
University of Nevada, silver, blue
University of Nevada-Las Vegas, scarlet, gray
Dartmouth College, green, white
Southern New Hampshire University, blue, gold
University of New Hampshire, blue, white
Caldwell University, red, gold
Centenary University, grey, navy blue
The College of New Jersey, blue, gold
Drew University, blue, green
Kean University, white, silver
Monmouth University, white, blue
Montclair State University, white, red
New Jersey Institute of Technology, scarlet red, white
Princeton University, orange, black
Ramapo College, white, maroon
Rider University, cranberry, white
Rowan University, brown, gold
Rutgers University, scarlet, white
Seton Hall University, white, blue
Steven’s Institute of Technology, grey, Stevens red
Stockton University, black, Columbia blue
William Paterson University, orange, black
Eastern New Mexico University, silver, green
New Mexico State University, crimson, white
University of New Mexico, cherry, silver
Western New Mexico University, purple, gold
Art Institute of New York City, red, white
Adelphi University, brown, gold
Bard College, red, white
Clarkson University, green, gold
Columbia University, Columbia blue, white
Cornell University, Carnelian red, white
CUNY (City University of New York) Queens College, blue, silver
Elmira College, purple, gold
Fordham University, purple, gold
Ithaca College, blue, gold
New York University, violet, white
Niagara University, purple, white
Siena College, green, gold
St. Bonaventure University, brown, white
St. Lawrence University, scarlet, brown
Syracuse University, orange, navy blue
University at Albany, purple, gold
University of Rochester, blue, yellow
Vassar College, burgundy, grey
Wells College, maroon, white
West Point (Army), black, gold
Appalachian State University, black, gold
Campbell University, orange, black
Central Piedmont Community College, black, green
Coastal Carolina University, teal, bronze
Davidson College, red, black
East Carolina University, purple, gold
Elon University, maroon, gold
Gardner Webb University, black, scarlet
Johnson and Wales University, white, blue
Johnson C. Smith University, navy blue, gold
North Carolina State University, red, white
North Carolina Central University, red, white
University of North Carolina, Carolina blue, white
University of North Carolina Charlotte (UNCC), green, white (gold accent)
University of North Carolina Greensboro (UNCG), gold, white
University of North Carolina Wilmington (UNCW), teal, navy
Duke University, teal, navy
Wake Forest University, black, gold
Western Carolina University, purple, gold
Minot State University, red, green
North Dakota State University, green, yellow
University of North Dakota, green, white
Bowling Green State University, orange, brown
Kenyon College, white, purple
Miami of Ohio, red, white
Mount Vernon Nazarene University, blue, green
Ohio State University, scarlet, grey
Ohio University, green, white
Otterbein University, green, white
University of Cincinnati, red, black
University of Dayton, red, columbia blue
University of Toledo, midnight blue, gold
Wright State University, green, gold
Oklahoma State University, orange, black
Oral Roberts University, Vegas gold, navy blue
Tulsa, gold, blue
University of Oklahoma, crimson, cream
Western Oklahoma State College, green, gold
Oregon State University, orange, black
Portland State University, white, green
University of Oregon, green, yellow
University of Portland, purple, white
Bucknell University, orange, blue
Carnegie Mellon University, grey, cardinal
Lehigh University, white, brown
Messiah College, navy blue, white
Montgomery County Community College, blue, black
Penn State University, navy blue, white
Robert Morris University, red, white
Susquehanna University, orange, maroon
Slippery Rock University, green, white
Temple University, cherry, white
University of Pennsylvania, blue, red
University of Pittsburgh, old gold, blue
University of Scranton, purple, white
West Chester University, purple, gold
Brown University, brown, cardinal
Bryant University, black, gold
Community College of Rhode Island, green, grey
Providence College, black, white
Rhode Island College, maroon, gold
University of Rhode Island (URI), royal (“Keaney”) blue, white
College of Charleston, red, white
The Citadel (The Military College of South Carolina), blue, white
Clemson University, orange, purple
Furman University, purple, white
South Carolina State University, garnet, blue
University of South Carolina, garnet, black
Wofford College, Old Gold, black
South Dakota State University (SDSU), blue, yellow
University of South Dakota, vermillion, white
Fisk University, gold, blue
Lee University, maroon & white Cleveland, TN
Middle Tennessee State University, royal blue, white
Tennessee State University, Reflex blue, white
Tennessee Tech University, purple, gold
Trevecca Nazarene University, purple, white
University of Memphis, blue, gray
University of Tennessee, orange, white
Vanderbilt University, gold, black
Austin College, gold, black
Baylor University, green, gold
Hardin Simmons University, purple, gold
Houston State University, orange, white
Lamar University, red, white
Midwestern State University, burgundy, gold
Rice University, Oxford (dark) blue, grey
Southern Methodist University, Harvard crimson, Yale blue
Stephen F. Austin University, purple, red
St. Edward’s University, blue, gold
Texas A&M University, maroon, white
Texas A&M University – Corpus Christi, true blue, true green
Texas Christian, purple, white
Texas-El Paso, blue, orange
Texas State University, maroon, gold
Texas Tech University, scarlet, black
Trinity University, maroon, white
University of Dallas, blue, white
University of Houston, red, white
University of Mary Hardin-Baylor, white, gold
University of North Texas, green, black
University of Texas, burnt orange, white
University of Texas (Arlington), orange, white
University of Texas (Dallas), white, orange
University of Texas (El Paso), blue, orange
University of Texas (San Antonio), orange, blue
University of the Incarnate Word, red, black
Brigham Young University, navy blue, gold
Southern Utah University, red, white
University of Utah, crimson, white
Utah State University, navy blue, white
Landmark College, blue, gold
University of Vermont, green, gold
Bridgewater College, maroon, gold
College of William & Mary, green, gold
George Mason University, green, gold
James Madison University, purple, gold
Liberty University, navy, red
Longwood University, royal blue, white
Lynchburg College, red/maroon, gray
Norfolk State University, green, gold
Old Dominion University, slate blue, silver
Radford University, red, black
Randolph-Macon College, black, lemon (yellow)
Roanoke College, maroon, gray; National blue and Mandarin yellow (original colors)
Saint Paul’s College, black, orange
Shenandoah University, red, blue
Strayer University, garnet, tan
University of Mary Washington, grey, navy blue
University of Richmond, red, blue
University of Virginia, orange, navy blue
Nicknames, Cavaliers, Wahoos
University of Virginia at Wise, red, gray
Virginia Commonwealth University (VCU), gold, black
Virginia Military Institute (VMI), red, white
Virginia State University, blue, orange
Virginia Tech (or Virginia Polytechnic Institute and State University), Chicago maroon, burnt orange
Virginia Union University, maroon, steel grey
Eastern Washington University, white, red
University of Washington, purple, gold
Washington State University, crimson, gray
Western Washington University, white, light blue
American University, red, blue
Catholic University of America, black, red
Gallaudet University, buff, blue
Georgetown University, Georgetown blue, gray
George Washington University, buff, blue
Howard University, Indigo blue, white
University of the District of Columbia, red, gold
Alderson-Broaddus College, navy & gold, gray accent
Davis and Elkins College, scarlet, white
Marshall University, kelly green, white.
Slogans, kelly green, white.
University of Charleston, maroon, gold
West Liberty University, black, gold
West Virginia State University, black, yellow
West Virginia University, old gold, blue
West Virginia Wesleyan College, orange, black
Marquette University, blue, gold
University of Wisconsin-Madison, red, white
University of Wisconsin-Milwaukee, gold, black
University of Wisconsin-Eau Claire, blue, gold
University of Wyoming, brown, Wyoming prairie gold
Air Force Academy (U.S.A.F.A), royal blue, silver
Coast Guard Academy, white, orange
Merchant Marine Academy (Kings Point), blue, gray
Military Academy (West Point), black, gray
Naval Academy (Annapolis), navy blue, gold